version: '3.8'

services:
  db:
    image: postgres:13-alpine
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./GuardBackand
    env_file: .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db
    volumes:
      - ./GuardBackand/:/app

  bot:
    build: ./GuardBot
    env_file: .env
    ports:
      - "${BOT_PORT}:${BOT_PORT}"
    depends_on:
      - backend
    volumes:
      - ./GuardBot/:/app

volumes:
  pgdata: